version: "2"
services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:1.19.5
    restart: always
    expose:
      - 80
      - 443
    volumes:
    - ./vol/certs:/etc/nginx/certs
    - ./vol/ssl:/etc/ssl
    - ./vol/config_nginx/:/etc/nginx/conf.d/:ro
    depends_on:
    - thehive
    - cortex
    - misp

  app:
    image: jc21/nginx-proxy-manager:latest
    ports:
    - "80:80"
    - "81:81"
    - "443:443"
    volumes:
    - ./config/config.json:/app/config/production.json
    - ./data:/data
    - ./letsencrypt:/etc/letsencrypt

  elasticsearch:
    image: elasticsearch:7.12.0
    environment:
    - http.host=0.0.0.0
    - discovery.type=single-node
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  cortex:
    image: thehiveproject/cortex:latest
    depends_on:
    - elasticsearch
    ports:
    - "0.0.0.0:9001:9001"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /tmp/cortex-jobs:/tmp/cortex-jobs
    - ./data/cortex:/app/data
  
  thehive:
    image: thehiveproject/thehive4:latest
    depends_on:
    - elasticsearch
    - cortex
    ports:
    - "0.0.0.0:9000:9000"
    command: 
      --cortex-port 9001
      --cortex-keys ${CORTEX_KEY}
    volumes:
    - ./thehive/application.conf:/etc/thehive/application.conf

  redis:
    image: redis:5.0.6

  db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - "MYSQL_USER=misp"
      - "MYSQL_PASSWORD=example"
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=misp"
    volumes:
      - "./vol/mysql_data:/var/lib/mysql"
    cap_add:
      - SYS_NICE

  misp:
    image: coolacid/misp-docker:core-latest
    depends_on:
      - redis
      - db
    ports:
      - "0.0.0.0:9500:443"
      - "0.0.0.0:9501:80"
    volumes:
      - "./vol/server-configs/:/var/www/MISP/app/Config/"
      - "./vol/logs/:/var/www/MISP/app/tmp/logs/"
      - "./vol/files/:/var/www/MISP/app/files"
      - "./vol/ssl/:/etc/nginx/certs"
    environment:
      - MISP_ADMIN_EMAIL=${MISP_ADMIN_EMAIL}
      - MISP_ADMIN_PASSPHRASE=${MISP_ADMIN_PASSPHRASE}
      - MISP_BASEURL=${MISP_BASEURL}
      - TIMEZONE=${TIMEZONE}
      - "REDIS_FQDN=redis"
      - "INIT=true"
      - "CRON_USER_ID=1"

volumes:
    mysql_data:

